name: RDP
on:
  workflow_dispatch:
jobs:
  secure-rdp:
    runs-on: windows-2025
    timeout-minutes: 3600
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ownership Verification
        run: |
          Write-Host "ToolboxLap.xyz - RDP Workflow"
          Write-Host "All rights reserved"

      - name: Create Directories
        run: |
          New-Item -Path "D:\link subscribe youtube channel" -ItemType Directory -Force
          New-Item -Path "D:\Script" -ItemType Directory -Force
          Write-Host "Directories created successfully"

      - name: Configure RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        run: |
          $password = "admin@123"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          if (-not (Get-LocalUser -Name "TOOLBOXLAP" -ErrorAction SilentlyContinue)) {
              New-LocalUser -Name "TOOLBOXLAP" -Password $securePass -AccountNeverExpires
          }
          Add-LocalGroupMember -Group "Administrators" -Member "TOOLBOXLAP" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "TOOLBOXLAP" -ErrorAction SilentlyContinue

      - name: Install Tor Browser
        run: |
          if (Test-Path ".\tor-browser-windows-x86_64-portable-14.5.6.exe") {
              Copy-Item ".\tor-browser-windows-x86_64-portable-14.5.6.exe" "$env:TEMP\tor-installer.exe"
              Start-Process -FilePath "$env:TEMP\tor-installer.exe" -ArgumentList "/S" -Wait
              Write-Host "Tor Browser installed from local file"
          } else {
              Write-Host "Tor Browser file not found, skipping installation"
          }

      - name: Install Python and Dependencies
        run: |
          # Check Python
          try {
              $pythonVersion = python --version
              Write-Host "Python found: $pythonVersion"
          } catch {
              # Install Python
              $pythonUrl = "https://www.python.org/ftp/python/3.11.9/python-3.11.9-amd64.exe"
              $pythonInstaller = "$env:TEMP\python-installer.exe"
              Invoke-WebRequest -Uri $pythonUrl -OutFile $pythonInstaller
              Start-Process -FilePath $pythonInstaller -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1" -Wait
              Remove-Item $pythonInstaller -Force
          }
          
          # Install packages
          if (Test-Path ".\requirements.txt") {
              python -m pip install --upgrade pip
              python -m pip install -r ".\requirements.txt"
              Write-Host "Python dependencies installed"
          }

      - name: Copy Python Scripts
        run: |
          # Copy scripts from repository to D:\Script\
          if (Test-Path ".\FINAL_3_WINDOWS_TRUSTWORTHY.py") {
              Copy-Item ".\FINAL_3_WINDOWS_TRUSTWORTHY.py" "D:\Script\"
              Write-Host "FINAL_3_WINDOWS_TRUSTWORTHY.py copied"
          }
          if (Test-Path ".\FINAL_3_WINDOWS_TRUSTWORTHY-original.py") {
              Copy-Item ".\FINAL_3_WINDOWS_TRUSTWORTHY-original.py" "D:\Script\"
              Write-Host "FINAL_3_WINDOWS_TRUSTWORTHY-original.py copied"
          }
          if (Test-Path ".\usa_residential_gui.py") {
              Copy-Item ".\usa_residential_gui.py" "D:\Script\"
              Write-Host "usa_residential_gui.py copied"
          }
          
          Write-Host "Script folder contents:"
          Get-ChildItem "D:\Script\" | ForEach-Object { Write-Host "  - $($_.Name)" }

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $retries++
          }
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned"
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Verify RDP
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "RDP connection test failed"
              exit 1
          }
          Write-Host "RDP connectivity verified"

      - name: Maintain Connection
        run: |
          Write-Host "=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: TOOLBOXLAP"
          Write-Host "Password: admin@123"
          Write-Host "==================="
          Write-Host ""
          Write-Host "Python Scripts Available in D:\Script\"
          Write-Host "- FINAL_3_WINDOWS_TRUSTWORTHY.py"
          Write-Host "- FINAL_3_WINDOWS_TRUSTWORTHY-original.py" 
          Write-Host "- usa_residential_gui.py"
          Write-Host ""
          while ($true) {
              Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C to terminate"
              Start-Sleep -Seconds 300
          }
